[project]
name = "graph-api-functions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "azure-identity>=1.25.3",
    "citygeo-secrets",
    "httpx>=0.28.1",
    "pydantic[email]>=2.13.4",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.uv.sources]
citygeo-secrets = { git = "https://github.com/CityOfPhiladelphia/citygeo_secrets.git" }

[tool.uv]
default-groups = []

[tool.ruff]
line-length = 80

[tool.mypy]
explicit_package_bases = true
ignore_missing_imports = true

[dependency-groups]
dev = [
    "fawltydeps>=0.20.0",
    "ipython>=9.16.1",
    "isort>=8.0.1",
    "mkdocstrings-python>=2.0.7",
    "mypy>=2.3.1",
    "pip>=26.2.1",
    "pytest>=9.1.1",
    "ruff>=0.16.3",
    "zensical>=0.0.57",
]
